---
# These tasks install CentOS specific requirements.

- name: Install EPEL
  yum: name={{ item }} state=installed
  with_items:
    - epel-release.noarch


- name: Install nginx
  yum: name=nginx state=installed update_cache=yes


- name: Install essential Python packages
  yum: name={{ item }} state=installed
  with_items:
    - python-virtualenv


