# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 21:54
from __future__ import unicode_literals

from django.db import migrations, models


def first_question(apps, schema_editor):
    Question = apps.get_model("polls", "Question")
    our_question = Question(question_text="What's your favourite Linux Distribution?", pub_date="2017-04-29T21:37:53Z")
    our_question.save()
    get_question = Question.objects.get(pk=1)
    get_question.choice_set.create(choice_text='Debian', votes=0)
    get_question.choice_set.create(choice_text='Red Hat Enterprise Linux', votes=0)
    get_question.choice_set.create(choice_text='Arch Linux', votes=0)
    get_question.save()


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(first_question),
    ]
