---
# Setting up gunicorn

- name: gunicorn directory
  file: path=/opt/tutorial/gunicorn state=directory owner=vagrant group=vagrant


- name: gunicorn pid directory
  file: path=/var/run/gunicorn_tutorial state=directory owner=vagrant group=vagrant mode=0644


- name: gunicorn init
  template: src=gunicorn-init.config.j2 dest=/opt/tutorial/gunicorn/gunicorn-init.config owner=vagrant group=vagrant


- name: gunicorn service
  template: src=gunicorn_tutorial.service.j2 dest=/etc/systemd/system/gunicorn_tutorial.service owner=root group=root mode=0644


- name: gunicorn logging
  template: src=gunicorn-logging.config.j2 dest=/opt/tutorial/gunicorn/gunicorn-logging.config owner=vagrant group=vagrant


- name: creating virtualenv
  command: virtualenv --unzip-setuptools --no-site-packages /opt/tutorial/virtualenv creates=/opt/tutorial/virtualenv


- name: Running pip install
  command: /opt/tutorial/virtualenv/bin/pip install -r /vagrant/tutorial/requirements.txt


- name: changing virtualenv permissions
  file: path=/opt/tutorial/virtualenv state=directory owner=vagrant group=vagrant recurse=yes


- name: populating our database for the first time
  command: /opt/tutorial/virtualenv/bin/python manage.py migrate --settings=tutorial.settings_env chdir=/vagrant/tutorial creates=/opt/tutorial/db.sqlite3


- name: gunicorn service state
  service: name=gunicorn_tutorial state=started enabled=yes
