---
# This playbook contains common plays that will be run on all nodes.

- name: creating directory home
  file: path="{{project_home_directory}}" state=directory owner=vagrant group=vagrant

- include: gunicorn.yml
- include: nginx.yml
