---
# This playbook contains common plays that will be run on all nodes.

- name: directory home
  file: path=/opt/tutorial state=directory owner=vagrant group=vagrant

- include: gunicorn.yml
- include: nginx.yml
