---
# Setting up gunicorn

- name: creating nginx home directory
  file: path=/opt/tutorial/nginx state=directory owner=vagrant group=vagrant


- name: Creating nginx pid directory
  file: path=/var/run/nginx_tutorial state=directory owner=nobody group=root mode=0644


- name: Setting up nginx config file
  template: src=nginx.config.j2 dest=/opt/tutorial/nginx/nginx.config owner=vagrant group=vagrant
  notify:
  - reload nginx


- name: Placing nginx systemd file
  template: src=nginx_tutorial.service.j2 dest=/etc/systemd/system/nginx_tutorial.service owner=root group=root mode=0644
  notify:
  - reload nginx


- name: Starting nginx
  service: name=nginx_tutorial state=started enabled=yes
