---
# Setting up gunicorn

- name: nginx directory
  file: path=/opt/tutorial/nginx state=directory owner=vagrant group=vagrant


- name: nginx pid directory
  file: path=/var/run/nginx_tutorial state=directory owner=nobody group=root mode=0644


- name: nginx config
  template: src=nginx.config.j2 dest=/opt/tutorial/nginx/nginx.config owner=vagrant group=vagrant


- name: nginx service
  template: src=nginx_tutorial.service.j2 dest=/etc/systemd/system/nginx_tutorial.service owner=root group=root mode=0644


- name: nginx service state
  service: name=nginx_tutorial state=started enabled=yes
