---
# Handler to handle restart notifications


- name: systemd restart gunicorn
  listen: "restart gunicorn"
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
  systemd:
    name: gunicorn_tutorial
    state: restarted
    daemon_reload: yes
    enabled: yes


- name: upstart restart gunicorn
  listen: "restart gunicorn"
  when:
    - ansible_distribution == "Ubuntu"
  service:
    name: gunicorn_tutorial
    state: restarted
    enabled: yes


- name: systemd reload nginx
  listen: "reload nginx"
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
  systemd:
    name: nginx_tutorial
    state: reloaded
    daemon_reload: yes
    enabled: yes

- name: upstart reload nginx
  listen: "reload nginx"
  when:
    - ansible_distribution == "Ubuntu"
  service:
    name: nginx_tutorial
    state: reloaded
    enabled: yes
